services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft Settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Failproof / Idempotency Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Log Retention (prevents disk fill-up with 500k rows)
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 1073741824

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # The Delay Detector (Consumer)
  # We scale this to 3 to match our 3 partitions
  delay-detector:
    build: .
    command: uv run faststream run consumer.py
    deploy:
      replicas: 3
    depends_on:
      - kafka
    environment:
      KAFKA_URL: kafka:9092
    volumes:
      - .:/app
    working_dir: /app

  # The Data Loader (Producer)
  # Run this manually or it will trigger on compose up
  data-producer:
    build: .
    command: uv run python producer.py
    depends_on:
      - kafka
    environment:
      KAFKA_URL: kafka:9092
    volumes:
      - .:/app
    working_dir: /app
    profiles: ["manual"] #prevents it from running automatically every time